FROM node:18-alpine

# Install Chromium and dependencies for Puppeteer
RUN apk add --no-cache \
      bash \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

COPY package.json ./
RUN npm install

COPY local_app/ ./local_app/
RUN mkdir -p ./docs
COPY docs/test_specification.md ./docs/test_specification.md
COPY docs/test_expected.md ./docs/test_expected.md

CMD ["npm", "test"]
